name: flutter_times
description: Example Flutter implementation of the NyTimes API.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  flutter_bloc: ^0.4.1
  bloc: ^0.7.0
  sembast: ^1.11.0
  path_provider: ^0.4.1
  json_annotation: ^2.0.0
  dio: ^1.0.9
  transparent_image: ^0.1.0
  webview_flutter: ^0.0.1
  url_launcher: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^2.0.0
  build_runner: ^1.1.2
  flutter_launcher_icons: ^0.7.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/launcher/rss_icon.png'
  adaptive_icon_background: '#009688'
  adaptive_icon_foreground: 'assets/launcher/rss_icon.png'
